name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [feature]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please complete the form below.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What should it do? What problem does it solve?
      placeholder: "A clear and concise description of the feature..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you imagine this feature working?
      placeholder: "It could work like this..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried other solutions/workarounds?
      placeholder: "I tried..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
